version: '3.8'

services:
  short_url_db:
    container_name: short_url_db
    image: postgres:17
    env_file:
      - .env.${ENV:-local}
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: always
    env_file:
      - .env.${ENV:-local}
    ports:
      - "5050:80"
    depends_on:
      - short_url_db

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  short_url_api:
    container_name: short_url_api
    restart: always
    build:
      context: .
      dockerfile: ./apps/short-url/Dockerfile
      args:
        PORT: 8000
    env_file:
      - .env.${ENV:-local}
    environment:
      DB_HOST: short_url_db
      DB_PORT: 5432
    ports:
      - "8000:8000"
    depends_on:
      - short_url_db
    volumes:
      - ./apps/urls:/app
      - /app/node_modules


