version: '3.8'

services:
  short_url_db:
    image: postgres:17
    env_file:
      - .env.${ENV:-local}
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  short_url_api:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env.${ENV:-local}
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
