version: '3.8'

services:
  short_url_db:
    image: postgres:17
    environment:
      POSTGRES_DB: short_url_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    ports:
      - "5433:5432"
  short_url_api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      PORT: 8000
