services:
  short_url_db:
    container_name: short_url_db
    image: postgres:17
    env_file:
      - ./apps/user/.env.${ENV:-local}
    environment:
      POSTGRES_DB: short_url_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - ./volumes/postgres-data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  short_url_api:
    container_name: short_url_api
    restart: always
    build:
      context: .
      dockerfile: ./apps/short-url/Dockerfile
      args:
        PORT: 8000
    env_file:
      - ./apps/short-url/.env.${ENV:-local}
    ports:
      - "8000:8000"
    depends_on:
      - short_url_db
    volumes:
      - .:/app
      - /app/node_modules


