openapi: "3.0.0"
info:
  version: 1.0.0
  title: Short URL API

paths:
  /link:
    post:
      summary: Create short url
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
      responses:
        "200":
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Link'
        "400":
          description: Ошибка валидации
    
    get:
      summary: Redirect to the original url
      requestBody:
        content:
          application/json:
            schema:
              type: object
              properties:
                url:
                  type: string
      responses:
        "301":
          description: ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Link'

  /link/:id:
    delete:
      summary: Delete short url
      responses:
        "200":
          description: ok


components:
  schemas:
    Link:
      type: object
      properties:
        id:
          type: string
          format: uuid
        originalUrl:
          type: string
        code:
          type: string
        shortUrl:
          type: string
        createdAt:
          type: string
          format: date
      required:
        - id
        - originalUrl
        - shortUrl
        - code
        - createdAt
